### ISSUE TITLE
Should the environment be included in the print when it is NULL (i.e. for primitive functions)

### ISSUE THREAD

**Issue by mdequeljoe** [r-lib/prettycode#11]
I notice that when primitive functions are printed via `prettycode` the NULL environment is included:
  
```r
prettycode::prettycode()
min
#> .Primitive("min")
#> NULL
```

from: 

https://github.com/r-lib/prettycode/blob/33c541f7f4256fde95a1f28800baff433b898430/R/print.R#L78

**Comment by gaborcsardi** [comment]
Yeah, it is not really informative, so we might as well leave it out. I don't think it is possible for a non-primitive function to have a `NULL` environment.

Do you want to submit a PR?

**Comment by mdequeljoe** [comment]
sure will do
