### ISSUE TITLE
Extra quote was outputted

### ISSUE THREAD

**Issue by pwang2** [r-lib/prettycode#18]
I was debugging a weird formatting issue here(https://github.com/r-lib/styler/issues/897), and the root cause was targeted to `prettycode`'s replace_in_place function.  Can you help diagnose why there is an extra quote before "An" was kept in the `replace_in_place` function? 

```
> highlight(styler::style_text('a <- c( "TΔ", "An")'))
[1] "a \033[32m<-\033[39m \033[36mc\033[39m\033[33m(\033[39m\033[33m\"TΔ\"\033[39m,\"\033[33m\"An\"\033[39m\033[33m)\033[39m"
```
![image](https://user-images.githubusercontent.com/1592014/148598120-3a76c2b9-9254-4c75-865c-07149f25ab12.png)

**Comment by gaborcsardi** [comment]
I cannot reproduce it on macOS, are you on a non-UTF8 locale? In general, it is best to only use ASCII characters in R code, in fact non-ASCII characters are even forbidden on CRAN.

**Comment by pwang2** [comment]
I tried both C.UTF-8 and en_US.UTF-8 locales and got the same problem.  I was able to reproduce on a new Ubuntu 18.04.6 LTS VM with new R installation 3.6.3.  I am trying to provide a reproduce step with docker now.

**Comment by pwang2** [comment]
I was able to reproduce using the following container.

```
docker run --rm -it r-base:3.6.3 bash

# In container R repl
install.packages(c("styler", "prettycode"))

library(prettycode)
highlight(styler::style_text('a <- c( "TΔ", "An")'))

```

**Comment by pwang2** [comment]
This might be helpful to investigate. 
![image](https://user-images.githubusercontent.com/1592014/148601822-38830201-2639-4b56-8441-368aac0fc546.png)

**Comment by pwang2** [comment]
Any Update?

**Comment by gaborcsardi** [comment]
No, do not use non-ascii characters in code.
