### ISSUE TITLE
Allow to configure the colors of prettycode

### ISSUE THREAD

**Issue by Tal500** [r-lib/prettycode#22]
I would like the ability to configure manually the color selection of prettycode.
Right now it just works as a sequence of 3 fixed colors.

This is crucial because of different backgrounds of different terminals.

**Comment by gaborcsardi** [comment]
See `?prettycode::default_style`.

**Comment by Tal500** [comment]
> See `?prettycode::default_style`.

Will check this out, thanks!

**Comment by gaborcsardi** [comment]
Also see `?cli::code_hightlight` and `?cli::?cli::code_theme_list`, in case you are already using cli.
