### ISSUE TITLE
Colorful output of base types

### ISSUE THREAD

**Issue by nbenn** [r-lib/prettycode#5]
I have really gotten used to output as produced by [jalvesaq/colorout](https://github.com/jalvesaq/colorout) and was wondering whether something like this was in-scope for `prettycode` or if you want to keep this package limited to syntax highlighting of function bodies.

**Comment by gaborcsardi** [comment]
I would not mind a nicer print method for lists and vectors in general, but I will not work on this in the near future. Data frame pretty printing is being solved in the tibble package.
