### ISSUE TITLE
Not working in R 3.5

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/prettycode#6]
Hello,

After updating to R 3.5 this no longer works for me. Did something change about how S3 functions are found in R 3.5? Doing `prettycode:::print.function()` still works, but it doesn't seem to be called anymore by default.

**Comment by gaborcsardi** [comment]
Yeah, this is because of the new S3 method search strategy of R. I am investigating workarounds.....

**Comment by gaborcsardi** [comment]
Fixed now in the GH version,  going to CRAN ASAP. Note that you need to call `prettycode::prettycode()` now, to turn it on, best to put the call in the `.Rprofile`.

**Comment by gaborcsardi** [comment]
Please re-open if you have problems.
