### ISSUE TITLE
Is it broken again?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/prettycode#9]
IDK what has changed again in R's S3 search, but in 3.6.0, `prettycode::prettycode()` does not work, apparently.....

**Comment by gaborcsardi** [comment]
OK, it seems that with the changes in https://github.com/lionel-/r-source/pull/4#issuecomment-373518924 (Third patch), there is no way to make prettycode work again with R 3.6.0.

That's a pity, it seems that I'll have to stay at R 3.5.3 forever now. :)

**Comment by gaborcsardi** [comment]
A workaround would be to define a `!` operator, and then type `!fun` instead of just `fun`. I think this is as good as it gets...

**Comment by IndrajeetPatil** [comment]
Yeah, I can confirm that on a Windows machine this doesn't work with `R 3.6.0`, even for pretty-print with `!` operator.

**Comment by gaborcsardi** [comment]
You probably don't have color support in your terminal/gui. If you think that it should work, then please provide more information about your platform.

**Comment by IndrajeetPatil** [comment]
It used to work on my computer, so I am pretty sure that my terminal does have color support:
https://twitter.com/patilindrajeets/status/1039538332777238528

**Comment by mdequeljoe** [comment]
This appears fixed in R 3.6.1. From the release notes:

> print()ing and auto-printing no longer differs for functions with
      a user defined print.function, thanks to Bill Dunlap's report.

https://stat.ethz.ch/pipermail/r-announce/2019/000643.html

**Comment by gaborcsardi** [comment]
@mdequeljoe It is fixed in R 3.6.1 indeed!

**Comment by IndrajeetPatil** [comment]
I can confirm that this is working again on a Windows machine as well! 👍 

![image](https://user-images.githubusercontent.com/11330453/62425282-6d3cb700-b6a7-11e9-85ac-f156eff59598.png)
